# Generated by Django 4.2.16 on 2026-05-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('admin_order', 'Admin — New order'), ('payment', 'Payment'), ('promotion', 'Promotion'), ('system', 'System'), ('review', 'Review')], default='system', max_length=20),
        ),
    ]
