# Generated by Django 4.2.16 on 2026-08-24 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu", "0001_initial"),
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="channel",
            field=models.CharField(
                choices=[("grocery", "Grocery"), ("restaurant", "Restaurant")],
                default="grocery",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="menu.menuitem",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="selected_modifiers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Snapshot: [{modifier_id, group, name, price_delta}, ...] — menu items only",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "channel")},
        ),
    ]
