# Generated by Django 4.2.16 on 2026-08-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("menu", "0001_initial"),
        ("orders", "0007_partial_refund_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="channel",
            field=models.CharField(
                choices=[("grocery", "Grocery"), ("restaurant", "Restaurant")],
                db_index=True,
                default="grocery",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="menu.menuitem",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="selected_modifiers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Snapshot: [{modifier_id, group, name, price_delta}, ...] — menu items only",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
            ),
        ),
    ]
