# Generated by Django 4.2.16 on 2026-08-24 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="menu/categories/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Menu categories",
                "db_table": "menu_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=300)),
                ("slug", models.SlugField(max_length=340, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Permanently on/off the menu",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Today's 86 list — off without removing the dish",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "dietary_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="e.g. vegan, vegetarian, gluten_free, halal, contains_nuts, spicy",
                    ),
                ),
                (
                    "prep_time_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="menu.menucategory",
                    ),
                ),
            ],
            options={
                "db_table": "menu_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModifierGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "selection_type",
                    models.CharField(
                        choices=[
                            ("single", "Single choice"),
                            ("multiple", "Multiple choice"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("min_select", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_select",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Blank = unlimited (selection_type=multiple only)",
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_groups",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "menu_modifier_groups",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Modifier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "price_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="menu.modifiergroup",
                    ),
                ),
            ],
            options={
                "db_table": "menu_modifiers",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="menu/items/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item_images",
                "ordering": ["-is_primary", "sort_order"],
            },
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category", "is_active", "is_available"],
                name="menu_items_categor_96acba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="menu_items_is_feat_fa68fc_idx",
            ),
        ),
    ]
