# Generated by Django 4.2.16 on 2026-04-28 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Darwin CBD, Palmerston', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('min_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_distance_km', models.DecimalField(decimal_places=2, help_text='Max radius in km', max_digits=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order total above which delivery is free', max_digits=10, null=True)),
                ('estimated_delivery_days', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('outside_zone_behaviour', models.CharField(choices=[('allow', 'Allow delivery with extra charge'), ('deny', 'Deny delivery outside zone'), ('contact', 'Contact customer for quote')], default='deny', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'delivery_zones',
                'ordering': ['sort_order', 'min_distance_km'],
            },
        ),
    ]
